theme: jekyll-theme-hacker
title: lixiyu's blog
description: [不积跬步，无以至千里]
lang: zh-cmn-Hans
#google_analytics: [Your Google Analytics tracking ID]


# gitalk  评论互动模块
gitalk:
  owner: lixiyu
  repo: lixiyu.github.io
  client_id: 769bd02c3ce238306853
  client_secret: 662e8db8c389bd04896d1a8abf8b3f0c5758f891




########### 集合, 分组管理文件 #################

collections_dir: notes
collections:
  arts:
    output: true
    permalink: /:collection/:title
  fill_map:
    output: false
    permalink: /:collection/:name
  tmp_show:
    output: true
    permalink: /:collection/:name
  chaos:
    output: true
    permalink: /:collection/:name
  bridge:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: arts
    values:
      layout: arts
  - scope:
      path: ""
      type: chaos
    values:
      layout: default
  - scope:
      path: ""
      type: tmp_show
    values:
      layout: architect
  - scope:
      path: ""
      type: bridge
    values:
      layout: bridge
