theme: jekyll-theme-hacker
title: ARTS
description: [A short description of your site's purpose]
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]


# Gitment
gitment_owner: lixiyu
gitment_repo: lixiyu.github.io
gitment_oauth:
    client_id: 4df19928d32c66e715ce
    client_secret: 90923b7877af194fc9d40250cdef958cb57411d7

