theme: jekyll-theme-hacker
title: lixiyu's blog
description: [不积跬步，无以至千里]
lang: zh-cmn-Hans
#google_analytics: [Your Google Analytics tracking ID]


# Gitment
gitment:
  owner: lixiyu
  repo: lixiyu.github.io
  oauth:
    client_id: 4df19928d32c66e715ce
    client_secret: 90923b7877af194fc9d40250cdef958cb57411d7




########### 集合, 分组管理文件 #################

collections_dir: notes
collections:
  arts:
    output: true
    permalink: /:collection/:title
  fill_map:
    output: false
    permalink: /:collection/:name
  tmp_show:
    output: true
    permalink: /:collection/:name
  chaos:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "arts"
    values:
      layout: arts
  - scope:
      path: ""
      type: "chaos"
    values:
      layout: default
  - scope:
      path: ""
      type: "tmp_show"
    values:
      layout: architect
